# Generated by Django 3.1.5 on 2021-09-04 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('bought', 'BOUGHT'), ('not available', 'NOT AVAILABLE')], default='pending', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 4, 9, 47, 5, 993225, tzinfo=utc))),
            ],
        ),
    ]
