# Generated by Django 3.1.5 on 2021-09-04 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryupload',
            old_name='quantity',
            new_name='itemquantity',
        ),
        migrations.AlterField(
            model_name='groceryupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 9, 59, 57, 51412, tzinfo=utc)),
        ),
    ]
