# Generated by Django 3.1.5 on 2021-09-04 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210904_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryupload',
            name='uploadedby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groceryupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 10, 47, 4, 952586, tzinfo=utc)),
        ),
    ]
